# Generated by Django 4.2.11 on 2025-07-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='icon',
            field=models.CharField(blank=True, default='fa-calendar-check', max_length=32, verbose_name='Ikona wydarzenia'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Wydarzenie cykliczne'),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_end',
            field=models.DateField(blank=True, null=True, verbose_name='Powtarzaj do (włącznie)'),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_type',
            field=models.CharField(choices=[('none', 'Brak'), ('daily', 'Codziennie'), ('weekly', 'Co tydzień'), ('monthly', 'Co miesiąc'), ('yearly', 'Co rok')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('urodziny', 'Urodziny'), ('imieniny', 'Imieniny'), ('rocznice', 'Rocznice'), ('przeglad', 'Przegląd'), ('ubezpieczenie', 'Ubezpieczenie'), ('inne', 'Wpisz własną kategorię')], max_length=20),
        ),
    ]
